# 配置参考 ： https://segmentfault.com/a/1190000004315890
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
#debug : true

spring: 
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 6000
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
    
  profiles:
    active: dev
      
#数据源配置      
  datasource:
    name: zftal_demo
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.71.19.135:1521:orcl
    username: zftal_demo
    password: zftal_demo
    type: com.zaxxer.hikari.HikariDataSource
    # HiKariCP的数据源配置：
    hikari: 
      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idle-timeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟 
      maxLifetime: 1800000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count) 

#日志级别
logging: 
  log4j:
    enabled: true
    table-name: ZFTAL_LOG_BIZ
  config: classpath:log4j2.xml
    